<?php

namespace App\Services;

use App\Models\Post;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Str;

/**
 * Builds and resolves post permalinks based on the active structure
 * (settings key `permalink_structure`, falling back to config('barta.permalink')).
 *
 * Because a post slug is globally unique, incoming requests are always
 * resolved by their final {slug} segment regardless of the prefix, which
 * lets the site switch permalink structures without breaking resolution.
 */
class PermalinkService
{
    public function structureKey(): string
    {
        return (string) setting('permalink_structure', config('barta.permalink', 'date'));
    }

    public function structure(): string
    {
        $key = $this->structureKey();

        if ($key === 'custom') {
            return $this->normalize((string) setting('permalink_custom', '/%category%/%postname%/'));
        }

        return config("barta.permalinks.$key", config('barta.permalinks.default'));
    }

    public function pathFor(Post $post): string
    {
        $date = $post->published_at ?? $post->created_at ?? now();

        $path = strtr($this->structure(), [
            '{year}' => $date->format('Y'),
            '{month}' => $date->format('m'),
            '{day}' => $date->format('d'),
            '{slug}' => $post->slug,
            '{category}' => optional($post->category)->slug ?? 'news',
            '{author}' => optional($post->author)->username ?? 'author',
            '{post_id}' => (string) $post->getKey(),
        ]);

        return trim($path, '/');
    }

    /** Convert WordPress-style tags into Barta's internal placeholders. */
    protected function normalize(string $structure): string
    {
        return strtr(trim($structure, '/'), [
            '%year%' => '{year}',
            '%monthnum%' => '{month}',
            '%day%' => '{day}',
            '%postname%' => '{slug}',
            '%category%' => '{category}',
            '%author%' => '{author}',
            '%post_id%' => '{post_id}',
        ]);
    }

    public function urlFor(Post $post): string
    {
        return url('/'.$this->pathFor($post));
    }

    /** Find a published post (or page) by its slug, or fail with 404. */
    public function resolveOrFail(string $slug): Post
    {
        return $this->publishedQuery()
            ->where('slug', $slug)
            ->firstOrFail();
    }

    /** Resolve both standard and WordPress-style custom permalink paths. */
    public function resolvePathOrFail(string $path): Post
    {
        $pathSegments = explode('/', trim($path, '/'));
        $structureSegments = explode('/', trim($this->structure(), '/'));

        if (count($pathSegments) === count($structureSegments)) {
            if (($index = array_search('{slug}', $structureSegments, true)) !== false) {
                return $this->resolveOrFail($pathSegments[$index]);
            }

            if (($index = array_search('{post_id}', $structureSegments, true)) !== false) {
                return $this->publishedQuery()->findOrFail((int) $pathSegments[$index]);
            }
        }

        // Backward-compatible fallback for URLs generated by an older structure.
        return $this->resolveOrFail(Str::afterLast(trim($path, '/'), '/'));
    }

    protected function publishedQuery(): Builder
    {
        return Post::query()->where(function ($query) {
            $query->published()->orWhere('type', 'page');
        });
    }
}
